<a href="https://colab.research.google.com/github/2303a51095/B2_PFDS_2303A51095/blob/main/Lab_03_14th_Aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Matrix Addition and Subtraction

In [3]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("A + B:\n", A + B)  # addition
print("A - B:\n", A - B)  # subtraction



Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


## 2. 2D Matrix Multiplication (Dot Product)

In [4]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

dot_res = np.dot(a, b)
print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Dot Product Result:\n", dot_res)

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Dot Product Result:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


#class activity

In [5]:
file_name = "student_data.txt"

name = input("Enter name: ")
marks = input("Enter marks: ")

with open(file_name, "a") as f:
    f.write(f"{name},{marks}\n")

print("\nAll Entries:")
with open(file_name, "r") as f:
    for line in f:
        n, m = line.strip().split(",")
        print(f"Name: {n}, Marks: {m}")

Enter name: ganesh
Enter marks: 66

All Entries:
Name: ganesh, Marks: 66
